# pip install pre-commit
# pre-commit install
# pre-commit run --all-files -v

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
            args: [--maxkb, '1000']
          - id: check-json
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: mixed-line-ending
          - id: fix-byte-order-marker
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier

files: \.(json|js|ts|jsx|tsx|astro)