/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Space_ship_lp_1: THREE.Mesh
    Space_ship_lp_2: THREE.Mesh
    Space_ship_lp_3: THREE.Mesh
    Space_ship_lp_4: THREE.Mesh
    Space_ship_lp_5: THREE.Mesh
  }
  materials: {
    ship_glass: THREE.MeshStandardMaterial
    ship_wings: THREE.MeshStandardMaterial
    ship_body: THREE.MeshStandardMaterial
    ship_thrusters: THREE.MeshStandardMaterial
    ship_body_details: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Space_ship_lp'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/ship.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Space_ship_lp" position={[-14.5, -0.27, -3.25]} rotation={[0.03, 1.19, 0.88]} scale={0}>
          <mesh name="Space_ship_lp_1" geometry={nodes.Space_ship_lp_1.geometry} material={materials.ship_glass} />
          <mesh name="Space_ship_lp_2" geometry={nodes.Space_ship_lp_2.geometry} material={materials.ship_wings} />
          <mesh name="Space_ship_lp_3" geometry={nodes.Space_ship_lp_3.geometry} material={materials.ship_body} />
          <mesh name="Space_ship_lp_4" geometry={nodes.Space_ship_lp_4.geometry} material={materials.ship_thrusters} />
          <mesh name="Space_ship_lp_5" geometry={nodes.Space_ship_lp_5.geometry} material={materials.ship_body_details} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ship.gltf')
