# fly.toml app configuration file generated for sw-cms on 2025-04-17T15:53:05-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sw-cms'
primary_region = 'gru'
kill_timeout = '5m0s'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'media'
  destination = '/opt/app/media'
  initial_size = '1gb'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 1337
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
