name: Deploy to Firebase

on:
  push:
    branches: [ main, dev ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Install, build, and upload your site
        uses: withastro/action@v0

      - name: Cache build save
        uses: actions/cache/save@v3
        with:
          path: dist
          key: ${{ runner.os }}-build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Cache build restore
        uses: actions/cache/restore@v3
        with:
          path: dist
          key: ${{ runner.os }}-build

      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SW_SPACE_SITE }}
          channelId: live
          expires: ~

    outputs:
      url: ${{ steps.deploy.outputs.details_url || 'https://spacewiz.dev/' }}

  analysis:
    if: ${{ github.ref_name != 'main' }}

    runs-on: ubuntu-latest
    needs: deploy

    permissions:
      contents: write

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Checkout the Lighthouse repository
        uses: actions/checkout@v3
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested

      - name: Analyze and generate badge
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ needs.deploy.outputs.url }}
