name: Deploy to Live

on:
  push:
    branches:
      - main
      - dev
  pull_request:
      branches:
        - '*'
        - '!main'
        - '!dev'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - run: echo ${{ github.ref_name }}

      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Install, build, and upload your site
        uses: withastro/action@v0

      - name: Cache build save
        uses: actions/cache/save@v3
        with:
          path: dist
          key: ${{ runner.os }}-build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Cache build restore
        uses: actions/cache/restore@v3
        with:
          path: dist
          key: ${{ runner.os }}-build

      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SW_SPACE_SITE }}
          channelId: ${{ github.ref_name == 'main' && 'line' || github.ref_name }}
          expires: ${{ github.ref_name == 'dev' && '30d' || '7d' }}

    outputs:
      url: ${{ steps.deploy.outputs.details_url }}

  analysis:
    runs-on: ubuntu-latest
    needs: deploy

    permissions:
      contents: write

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Checkout the Lighthouse repository
        uses: actions/checkout@v3
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested

      - name: Analyze and generate badge
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ needs.deploy.outputs.url }}
