name: Deploy to Preview

on:
  pull_request:

jobs:
  deploy_to_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2

      - name: Install, build, and upload your site
        uses: withastro/action@v0

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SW_SPACE_SITE }}'

      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: '${{ secrets.GITHUB_TOKEN }}'
          ref: ${{ github.ref_name }}
      - uses: actions/checkout@v3
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested
      - uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{steps.deploy.outputs.url}}
