name: Lighthouse Analysis

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to be checked'
        required: true
        type: string
        default: 'https://spacewiz.dev/'
      commit_message:
        description: 'Commit message'
        required: true
        default: 'Lighthouse Results Added'

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Checkout the Lighthouse repository
        uses: actions/checkout@v3
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested

      - name: Analyze and generate badge
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ inputs.url }}
          user_name: ${{ github.actor }}
          commit_message: ${{ github.event.inputs.commit_message }}