name: Lighthouse Analysis

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL da página analisada'
        required: true
        type: string
        default: 'https://spacewiz.dev/'

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Checkout the Lighthouse repository
        uses: actions/checkout@v3
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested

      - name: Analyze and generate badge
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ inputs.url }}
